### ISSUE TITLE
Сообщить данные для получения сертификата финалиста

### ISSUE THREAD

**Issue by alehinsasha** [RoxyRedFlame/FinalTask#10]
В комментарии к этому issue напишите ваши:
- Имя Фамилию (в дательном падеже)
- Адрес электронной почты, на которую выслать сертификат

**Comment by RoxyRedFlame** [comment]
Шиловой Светлане Леонидовне, RoxyRedFlame@gmail.com

**Comment by alehinsasha** [comment]
Поздравительное письмо отправлено на указанный адрес! Прошу подтвердить получение.

**Comment by RoxyRedFlame** [comment]
Все получено! Спасибо за курс, за доступную подачу материала!
