### ISSUE TITLE
Разработка по промышленным стандартам

### ISSUE THREAD

**Issue by alehinsasha** [RoxyRedFlame/FinalTask#7]
- [x] Одна функциональность = одна фича и сценарии проверяющие работу этой фичи/функциональности
- [x] Использование фикстур
- [x] Повторное использование шагов (собственная библиотека шагов)
- [x] Фичи из воздуха
- [x] Детализация фичи

**Comment by RoxyRedFlame** [comment]
Под  Одна функциональность = одна фича подразумевается, что фича на простое проведение документа Продажа и фича на проверку достаточности остатков при проведении  это две разные фичи? И автоматическое заполнение реквизита акции и фиксация расходов на акции тоже 2 разные фичи?

**Comment by RoxyRedFlame** [comment]
что подразумевается под детализацией фичи?

**Comment by RoxyRedFlame** [comment]
Пункт Использование фикстур. В каждой обработке проверки поведения в шаге Подготовка данных  добавлено  ЗагрузитьFixtureИзМакета, макеты к обработкам тоже добавлены. Или я не так понимаю данный пункт?

**Comment by RoxyRedFlame** [comment]
В коммите "#7  #4 В каталоге features создала каталог, в который буду добавлять свои библиотечные шаги. Создала библиотечную фичу подготовки данных  из макета "ТоварДляПокупки", служебную обработку.  Фича и обработка ОтражениеОперацииЗакупкиТоваровВДокументеПокупка изменена с импользованием новой служебной фичи." Ссылка на 4 задачу ошибочна, д.б #1.

**Comment by RoxyRedFlame** [comment]
Одна функциональность = одна фича и сценарии проверяющие работу этой фичи/функциональности. Для этого разделила фичу АвтоматическаяПодстановкаАктуальнойНаДатуАкции на 2, по кол-ву функционала.
