### ISSUE TITLE
Демонстрация работ заказчику

### ISSUE THREAD

**Issue by alehinsasha** [RoxyRedFlame/FinalTask#9]
**Что нужно сделать**
1. Выгрузить конфигурацию в файлы (конфигуратор → конфигурация → выгрузить конфигурацию в файлы → <ИмяРепозиторияФинальногоЗадания>\src\cf);
2. Закоммитить и отправить во внешний репозиторий.

**Особенности**
- Приступать к выполнению этой задачи нужно после того как закроете все созданные мной issue.
- В публичный внешний репозиторий, нельзя помещать код из типовых конфигураций 1С!

**Comment by RoxyRedFlame** [comment]
Ошиблась с привязкой коммита к задаче, вместо 8 указала 9. Впоследствии исправила.

**Comment by alehinsasha** [comment]
Осталось выгрузить конфигурацию в \src\cf и отправить сюда.

**Comment by RoxyRedFlame** [comment]
Сделано, Только у меня вопрос. До того, как в файл с фичами  добавить служебную библиотечную фичу, я прогоняла все сценарии сразу из папки features. Все сценарии выполнялись успешно. Но теперь при прогоне всей папки в отбор попадает библиотечная фича со своей обработкой, которая  свою библиотечную функцию в сценарии к задаче успешно выполняет, а сама при нажатии "выполнить сценарии" стопорит выполнение всех сценариев, так как ее сценарий тоже пытается выполнятся. Так и должно быть? Или я что-то еще должна добавить в служебную фичу?

**Comment by alehinsasha** [comment]
@RoxyRedFlame я при разработке добиваюсь что библиотечные шаги то же отрабатывают. Они же то же должны проверяться. Но если что можно указать какой-нибудь (свой) тег в фиче, мол она библиотечная, а в vanessa-behavior указать этот тег как исключение. Но лучше первый вариант.
